from typing import Tuple
from pydantic import BaseModel
from openai import AsyncOpenAI, AsyncAzureOpenAI
from app.config import settings
import json

class ValidationResult(BaseModel):
    is_valid: bool
    feedback: str

VALIDATOR_SYSTEM_PROMPT = """You are a role validator for a debate system. 
You will be given a proposition (topic), a role (FOR or AGAINST), and a response generated by an agent.
Your job is to ensure the agent strictly adhered to its role.

If role is FOR, the agent MUST support the proposition.
If role is AGAINST, the agent MUST oppose the proposition.

Return a JSON with 'is_valid' (boolean) and 'feedback' (string with correction instructions if invalid, or empty if valid).
"""

class RoleValidator:
    def __init__(self):
        self.model = settings.MODEL_NAME
        if settings.OPENAI_API_TYPE.lower() == "azure":
            self.client = AsyncAzureOpenAI(
                api_key=settings.OPENAI_API_KEY,
                api_version=settings.AZURE_OPENAI_API_VERSION,
                azure_endpoint=settings.AZURE_OPENAI_ENDPOINT
            )
        else:
            client_kwargs = {"api_key": settings.OPENAI_API_KEY}
            if settings.OPENAI_BASE_URL:
                client_kwargs["base_url"] = settings.OPENAI_BASE_URL
            self.client = AsyncOpenAI(**client_kwargs)

    async def validate(self, topic: str, role: str, response_text: str) -> ValidationResult:
        messages = [
            {"role": "system", "content": VALIDATOR_SYSTEM_PROMPT},
            {"role": "user", "content": f"Topic: {topic}\nRole: {role}\nAgent Response: {response_text}"}
        ]
        
        try:
            response = await self.client.beta.chat.completions.parse(
                model=self.model,
                messages=messages,
                response_format=ValidationResult,
                temperature=0.0
            )
            return response.choices[0].message.parsed
        except Exception:
            # Fallback
            messages[0]["content"] += "\nReturn ONLY valid JSON."
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                response_format={"type": "json_object"},
                temperature=0.0
            )
            return ValidationResult.model_validate_json(response.choices[0].message.content)
